ln Links mkdir
ln Links ls
ln Links rmdir
ln Links touch
ln Links cat
ln Links rm
ln Links ln-s
ln Links readlink
ln Links cat-link
ln Links rm-link
ln Links ln
ln Links rm-hardlink
ln Links stat
ln Links chmod
